from . import gp_config
from . import gp_sync_service
from . import sale_order
from . import stock_picking
from . import product_template
from . import res_partner
from . import gp_sync_log
from . import gp_shipment_notification
from . import product_sync